package com.contable.services;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.11.fuse-000281-redhat-3
 * 2018-09-01T02:14:56.986-05:00
 * Generated source version: 3.1.11.fuse-000281-redhat-3
 * 
 */
@WebServiceClient(name = "ContableService", 
                  wsdlLocation = "file:/Users/arkazero/workspaceFuse11/Contabilidad/src/main/resources/ContableService.wsdl",
                  targetNamespace = "http://services.contable.com/") 
public class ContableService_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://services.contable.com/", "ContableService");
    public final static QName ContableServicePort = new QName("http://services.contable.com/", "ContableServicePort");
    static {
        URL url = null;
        try {
            url = new URL("file:/Users/arkazero/workspaceFuse11/Contabilidad/src/main/resources/ContableService.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ContableService_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/Users/arkazero/workspaceFuse11/Contabilidad/src/main/resources/ContableService.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ContableService_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ContableService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ContableService_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public ContableService_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public ContableService_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public ContableService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns ContableService
     */
    @WebEndpoint(name = "ContableServicePort")
    public ContableService getContableServicePort() {
        return super.getPort(ContableServicePort, ContableService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ContableService
     */
    @WebEndpoint(name = "ContableServicePort")
    public ContableService getContableServicePort(WebServiceFeature... features) {
        return super.getPort(ContableServicePort, ContableService.class, features);
    }

}
